### ISSUE TITLE
Progressing PFObject using parse-server-example

### ISSUE THREAD

**Issue by otto1020** [ParsePlatform/parse-server-example#51] opened 2016-02-09 09:20 UTC
I am working on migration parse.

So I could migrate Parse DB to MongoDB using MongoLab.
Also I could change parse-server-example;
- add cloud code(for mandrill-api and twilio) in main.js.(this works very well)
- deploy to Heroku.

However, I have some issues here.

On iOS development side, when the user logs in, app don't progress any PFObject.
- if I am going to change user's profile(string, boolean, image and so on), I get error message
[Error]: Can't upload a file that doesn't exist locally. (Code: 151, Version: 1.12.0)

- If I am going to download the user's photo, I get error message.
[Error]: Can't download a file that doesn't exist on the server or locally. (Code: 151, Version: 1.12.0)

Also I found a strange issue.
After migration, I created a new account on my app.(without user's photo)
First, it seems it works very well

But If I upload user's photo, connection error occurs.

What's matter?

I hope you can help me.

Thanks

**Comment by drew-gross** [comment] 2016-02-09 17:23
Can you run the server with VERBOSE=1 and tell us what the server outputs when you try to make a request and it fails?

**Comment by otto1020** [comment] 2016-02-09 17:57
Thanks a lot.

I ran the server in terminal.
`$ npm start VERSOSE=1`

And I ran my app.
Here is my code.
`[currentUser setValue:@"YES" forKey:PF_USER_ONLINE_STATUS];
    [currentUser saveInBackgroundWithBlock:^(BOOL succeeded, NSError *error) {
        if (!error) {
            NSLog(@"Success!");
        } else
            [ProgressHUD showError:error.localizedDescription Interaction:YES];
    }];`

But I can get nothing on my server. Also I got same result on my app

I feel this request don't go to server.

**Comment by drew-gross** [comment] 2016-02-09 18:09
Sorry, I mean `VERBOSE=1 npm start`

**Comment by otto1020** [comment] 2016-02-09 18:16
the result is same

**Comment by otto1020** [comment] 2016-02-09 18:24
Hi,

I just tried with postman.

So I got the result as following 

`GET /parse/classes/SubCategory/kTRcTBd3Fg { host: 'localhost:1337',
  connection: 'keep-alive',
  'cache-control': 'no-cache',
  'x-parse-master-key': 'myMasterKey',
  'x-parse-application-id': 'myAppId',
  'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36',
  'postman-token': '17b21b35-5e18-d1d0-ed47-6109eb856bd8',
  accept: '*/*',
  'accept-encoding': 'gzip, deflate, sdch',
  'accept-language': 'en-US,en;q=0.8' } {}
response: {
  "objectId": "kTRcTBd3Fg",
  "createdAt": "2015-09-03T08:36:52.865Z",
  "updatedAt": "2015-09-03T08:37:05.004Z",
  "subcategory_id": 23,
  "subcategory_name": "Happy Dream",
  "category_id": 2
}`

**Comment by drew-gross** [comment] 2016-02-09 18:27
I think this is a duplicate of https://github.com/ParsePlatform/parse-server/issues/206, we will track the issue there.

**Closed by drew-gross** 2016-02-09 18:27 UTC
